config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: "deadpool", path_names: {sign_in: "startTheFun"}, controllers: { sessions: "admin/sessions" }
  devise_for :partners, controllers: { registrations: "partner_controllers/registrations", sessions: "partner_controllers/sessions" }
  devise_for :users, controllers: { registrations: "user_controllers/registrations", sessions: "user_controllers/sessions" }

  resources :users, only: [:show, :edit]
  resources :partners, only: [:show, :edit]
  resources :events, only: [:index, :new, :destroy]
  resources :quests

  namespace :events do
    resources :presentations, except: [:index, :destroy]
    resources :courses, except: [:index, :destroy]

    namespace :courses do
      resources :presentations, only: [:show, :edit, :update]
    end
  end

  root "home#index"
  delete "logout", to: "home#logout"

  # User subpage aliases
  get "users/:id?sp=personal", to: "users#show", as: "user_personal"
  get "users/:id?sp=psychological", to: "users#show", as: "user_psychological"
  get "users/:id?sp=physical", to: "users#show", as: "user_physical"
  get "users/:id?sp=skill", to: "users#show", as: "user_skill"
  get "users/:id?sp=quest", to: "users#show", as: "user_quest"

  ##########
  # EVENTS #
  ##########
  
  # Occurrence subscription and payment
  patch "events/occurrences/:occurrence_id/subscription", to: "events/occurrences#subscription", as: "subscription"
  patch "events/occurrences/:occurrence_id/pay", to: "events/occurrences#pay", as: "pay_occurrence"
  
  # Confirm users individually.
  get "events/occurrences/:occurrence_id/checkin", to: "events/occurrences#checkin", as: "checkin"
  patch "events/occurrences/:occurrence_id/checkin/confirm_single_user", to: "events/occurrences#confirm_single_user", as: "confirm_single_user"
  patch "events/occurrences/:occurrence_id/checkin/undo", to: "events/occurrences#unconfirm", as: "undo_confirmation"

  # Confirm multiple users at once
  get "events/occurrences/:occurrence_id/checkin_list", to: "events/occurrences#checkin_list", as: "checkin_list"
  patch "events/occurrences/:occurrence_id/checkin_list", to: "events/occurrences#confirm_list", as: "confirm_list"

  # Finalize user confirmation
  patch "events/occurrences/:occurrence_id/checkin/finalize", to: "events/occurrences#finalize", as: "finaliza_occurrence"

  # Commenting
  post "events/:event_id/comment", to: "events#create_comment", as: "new_comment"
  delete "events/:event_id/comment/:comment_id", to: "events#destroy_comment", as: "destroy_comment"

  #########
  # ADMIN #
  #########

  get "deadpool/hq", to: "admin#show", as: "hq"
  get "deadpool/hq", to: "admin#show", as: "admin_root"
  
    # User Manager #
    get "deadpool/userManager", to: "admin/user_manager#show", as: "user_manager"
    post "deadpool/userManager/get", to: "admin/user_manager#get_user", as: "get_user"
    post "deadpool/userManager/adjust_credit", to: "admin/user_manager#adjust_credit", as: "adjust_credit"
  
    # Partner Manager #
    get "deadpool/partnerManager/(:id)", to: "admin/partner_manager#show", as: "partner_manager"
    post "deadpool/partnerManager/selectPartner", to: "admin/partner_manager#select_partner", as: "admin_select_partner"
    patch "deadpool/partnerManager/deselectPartner", to: "admin/partner_manager#deselect_partner", as: "admin_deselect_partner"
  
  
  get "deadpool/eventManager", to: "admin/event_manager#show", as: "event_manager"
  get "deadpool/questManager", to: "admin/quest_manager#show", as: "quest_manager"
  patch "deadpool/change_password", to: "admin#update_password", as: "change_admin_password"
  
  
  ##########
  # OTHERS #
  ##########

  # Quests
  #get "users/:id/quests", to: "users#show_quests", as: "user_quests"
  patch "users/:id/change_quest_visibility", to: "users#quest_visibility", as: "user_quest_visibility"
  patch "quests/:id/assignment", to: "quests#assignment", as: "quest_assignment"

  post "ratings/new", to: "ratings#create", as: "rating"

  ###########
  # TESTING #
  ###########
  
  # These are needed for rapid user/partner registration and changing them.
  post "test_tools/new_user", to: "test_tools#new_user", as: "test_new_user"
  post "test_tools/change_user", to: "test_tools#change_user", as: "test_change_user"
end

app/models/quests/generic_quest.rb
class Quests::GenericQuest < Quests::Quest
end

app/models/quests/quest.rb
class Quests::Quest
  include Mongoid::Document

  field :title, type: String, default: ""
  field :description, type: String, default: ""

  embeds_many :tasks, class_name: "Quests::Task"

  has_and_belongs_to_many :dependencies, class_name: "Quests::Quest", inverse_of: :depends_on_me
  has_and_belongs_to_many :depends_on_me, class_name: "Quests::Quest", inverse_of: :dependencies

  accepts_nested_attributes_for :tasks, :dependencies, allow_destroy: true

  def to_react_data
    {id: _id.to_s, title: title, description: description, tasks: tasks.map(&:to_react_data),
     dependencies: dependencies.map{|d| {id: d._id.to_s, title: d.title}}}
  end
end

app/models/quests/task.rb
class Quests::Task
  include Mongoid::Document

  field :description, type: String
  field :completed, type: Boolean, default: false

  embedded_in :quest
  belongs_to :event, optional: true

  def completed?
    completed
  end

  def to_react_data
    evt = event ? {event_title: event.title, event_id: event._id.to_s} : {}
    evt.merge({id: _id.to_s, description: description, completed: completed})
  end
end

app/models/quests/user_quest.rb
class Quests::UserQuest < Quests::Quest
  belongs_to :user
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
	include ApplicationHelper

  before_action :verify_admin, only: [:new, :create, :edit, :update, :destroy]

	def index
		@quests = ::Quests::Quest.all
	end

	def show
		@quest = ::Quests::Quest.find(params[:id])
	end

	def new
		render("quests/new", locals: {quest: Quests::GenericQuest.new, all_quests: all_quests})
	end

	def edit
		quest = ::Quests::Quest.find(params[:id])

		render("quests/edit", locals: {quest: quest, all_quests: all_quests})
	end

	def create
		par = quest_params
		quest = ::Quests::GenericQuest.new(par)
		quest.save!

    respond_to do |format|
      format.js{ head :ok }
    end
	end

	def update
		par = quest_params
		quest = ::Quests::Quest.find(params[:id])
		quest.dependencies.clear unless par.include?(:dependency_ids)
		quest.update_attributes(par)


		respond_to do |format|
			format.js{ head :ok }
		end
	end

	def destroy
		@quest = ::Quests::Quest.find(params[:id])
		@quest.destroy

		redirect_to quests_path
	end

	def assignment
		@changed = :no
		if user_signed_in?
			@quest = ::Quests::Quest.find(params[:id])
			if current_user.assigned_quests.include? @quest
				current_user.assigned_quests.delete(@quest)
				@changed = :declined
			elsif user_eligible_for_quest? current_user, @quest
				current_user.assigned_quests << @quest
				@changed = :assigned
			end
		end

		respond_to do |format|
			format.js
		end
	end

	protected
		def quest_params
			params.require(:quest).permit(:title, :description, dependency_ids: [],
																		tasks_attributes: [:id, :description, :event_id, :_destroy])
		end

		def all_quests
			Quests::Quest.all.map{|q| {id: q._id.to_s, title: q.title}}
		end

    def verify_admin
      unless admin_signed_in?
        redirect_to root_path
      end
    end
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/quests/_form.html.erb
<%= form_for @quest, url: url do |f| %>
	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</p>

	<h2>Feladatok</h2>
	<%= f.nested_fields_for :tasks do |task| %>
		<p>
			<%= task.remove_nested_fields_link "Feladat törlése" %>
		</p>
		<p>
			<%= task.label :description %>
			<%= task.text_area :description %>
		</p>
		<p>
			Esemény (opcionális): <%= task.collection_select :event_id, Event.all, :id, :long_name, include_blank: true %>
		</p>
	<% end %>
	<p>
		<%= f.add_nested_fields_link :tasks, "Új feladat hozzáadása" %>
	</p>
	<h2>Előfeltételek</h2>
	<%= f.nested_fields_for :dependencies do |dep| %>
		<p>
			 <%= dep.collection_select :id, ::Quests::Quest.all, :id, :title %> - <%= dep.remove_nested_fields_link "Törlés" %>
		</p>
	<% end %>
	<p>
		<%= f.add_nested_fields_link :dependencies, "Új előfeltétel választása" %>
	</p>

	<%= f.submit submit_text %>

<% end %>

app/views/quests/assignment.js.erb
<% unless @changed == :no %>
	$("#quest_<%= @quest._id %>").html("<%= escape_javascript( link_to(@quest.title, quest_path(@quest)) + ' ' + get_quest_assign_link(@quest) ) %>")
<% end %>

app/views/quests/edit.html.erb
<h1>Küldetés módositása</h1>
<%= react_component("QuestForm", quest.to_react_data.merge({all_quests: all_quests,
                                                            formUrl: "/quests/#{quest._id.to_s}",
                                                            formMethod: "put",
                                                            authenticity_token: form_authenticity_token})) %>

<%= link_to(I18n.t('labels.general.cancel'), quest_path(quest)) %>

app/views/quests/index.html.erb
<h1>Küldetések</h1>
<ol>
	<% @quests.each do |q| %>
		<li>
			<%= link_to q.title, quest_path(q) %> - <%= link_to "Módositás", edit_quest_path(q) %>, <%= link_to "Törlés", quest_path(q),
						method: :delete,
						data: { confirm: "Biztosan törölni szeretnéd ezt a küldetést?" } %>
		</li>
	<% end %>
</ol>

app/views/quests/new.html.erb
<h1>Új küldetés</h1>
<%= react_component("QuestForm", quest.to_react_data.merge({all_quests: all_quests,
                                                            formUrl: "/quests",
                                                            formMethod: "post",
                                                            authenticity_token: form_authenticity_token})) %>
<%= link_to(I18n.t('labels.general.back'), quest_manager_path) %>

app/views/quests/show.html.erb
<h2><%= @quest.title %></h2>
<p>
	<%= link_to(I18n.t('labels.general.edit'), edit_quest_path(@quest)) %>
</p>
<span>Leirás:</span>
<p>
	<%= @quest.description %>
</p>
<h3>Feladatok</h3>
<ol>
	<% @quest.tasks.each do |t| %>
		<li>
			<p>
				<%= t.description %>
			</p>
			<% unless t.event.nil? %>
				<p>
					Kapcsolódó esemény: <%= link_to t.event.long_name, event_path(t.event) %>
				</p>
			<% end %>
		</li>
	<% end %>
</ol>
<h3>Előkövetelmények</h3>
<ul>
	<% @quest.dependencies.each do |d| %>
		<li>
			<p>
				<%= d.title %>
			</p>
		</li>
	<% end %>
</ul>