config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: "deadpool", path_names: {sign_in: "startTheFun"}, controllers: { sessions: "admin/sessions" }
  devise_for :partners, controllers: { registrations: "partner_controllers/registrations", sessions: "partner_controllers/sessions" }
  devise_for :users, controllers: { registrations: "user_controllers/registrations", sessions: "user_controllers/sessions" }

  resources :users, only: [:show, :edit]
  resources :partners, only: [:show, :edit]
  resources :events, only: [:index, :new, :destroy]
  resources :quests

  namespace :events do
    resources :presentations, except: [:index, :destroy]
    resources :courses, except: [:index, :destroy]

    namespace :courses do
      resources :presentations, only: [:show, :edit, :update]
    end
  end

  root "home#index"
  delete "logout", to: "home#logout"

  # User subpage aliases
  get "users/:id?sp=personal", to: "users#show", as: "user_personal"
  get "users/:id?sp=psychological", to: "users#show", as: "user_psychological"
  get "users/:id?sp=physical", to: "users#show", as: "user_physical"
  get "users/:id?sp=skill", to: "users#show", as: "user_skill"
  get "users/:id?sp=quest", to: "users#show", as: "user_quest"

  ##########
  # EVENTS #
  ##########
  
  # Occurrence subscription and payment
  patch "events/occurrences/:occurrence_id/subscription", to: "events/occurrences#subscription", as: "subscription"
  patch "events/occurrences/:occurrence_id/pay", to: "events/occurrences#pay", as: "pay_occurrence"
  
  # Confirm users individually.
  get "events/occurrences/:occurrence_id/checkin", to: "events/occurrences#checkin", as: "checkin"
  patch "events/occurrences/:occurrence_id/checkin/confirm_single_user", to: "events/occurrences#confirm_single_user", as: "confirm_single_user"
  patch "events/occurrences/:occurrence_id/checkin/undo", to: "events/occurrences#unconfirm", as: "undo_confirmation"

  # Confirm multiple users at once
  get "events/occurrences/:occurrence_id/checkin_list", to: "events/occurrences#checkin_list", as: "checkin_list"
  patch "events/occurrences/:occurrence_id/checkin_list", to: "events/occurrences#confirm_list", as: "confirm_list"

  # Finalize user confirmation
  patch "events/occurrences/:occurrence_id/checkin/finalize", to: "events/occurrences#finalize", as: "finaliza_occurrence"

  # Commenting
  post "events/:event_id/comment", to: "events#create_comment", as: "new_comment"
  delete "events/:event_id/comment/:comment_id", to: "events#destroy_comment", as: "destroy_comment"

  #########
  # ADMIN #
  #########

  get "deadpool/hq", to: "admin#show", as: "hq"
  get "deadpool/hq", to: "admin#show", as: "admin_root"
  
    # User Manager #
    get "deadpool/userManager", to: "admin/user_manager#show", as: "user_manager"
    post "deadpool/userManager/get", to: "admin/user_manager#get_user", as: "get_user"
    post "deadpool/userManager/adjust_credit", to: "admin/user_manager#adjust_credit", as: "adjust_credit"
  
    # Partner Manager #
    get "deadpool/partnerManager/(:id)", to: "admin/partner_manager#show", as: "partner_manager"
    post "deadpool/partnerManager/selectPartner", to: "admin/partner_manager#select_partner", as: "admin_select_partner"
    patch "deadpool/partnerManager/deselectPartner", to: "admin/partner_manager#deselect_partner", as: "admin_deselect_partner"
  
  
  get "deadpool/eventManager", to: "admin/event_manager#show", as: "event_manager"
  get "deadpool/questManager", to: "admin/quest_manager#show", as: "quest_manager"
  patch "deadpool/change_password", to: "admin#update_password", as: "change_admin_password"
  
  
  ##########
  # OTHERS #
  ##########

  # Quests
  #get "users/:id/quests", to: "users#show_quests", as: "user_quests"
  patch "users/:id/change_quest_visibility", to: "users#quest_visibility", as: "user_quest_visibility"
  patch "quests/:id/assignment", to: "quests#assignment", as: "quest_assignment"

  post "ratings/new", to: "ratings#create", as: "rating"

  ###########
  # TESTING #
  ###########
  
  # These are needed for rapid user/partner registration and changing them.
  post "test_tools/new_user", to: "test_tools#new_user", as: "test_new_user"
  post "test_tools/change_user", to: "test_tools#change_user", as: "test_change_user"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render('home/index', locals: {disable_main_container: true})
  end

  def logout
    sign_out_all_scopes

    redirect_to root_path
  end
end

app/views/home/_partner_login_form.html.erb
<%= form_for(:partner, url: session_path(:partner), html: {class: "flex-form collapse", id: "partner-login-form"}) do |f| %>
  <ul>
    <li>
      <%= f.label :email, class: "sr-only" %>
      <%= f.email_field :email, {autofocus: true, placeholder: "Email cím"} %>
    </li>
    <li>
      <%= f.label :password, class: "sr-only" %>
      <%= f.password_field :password, {autocomplete: "off", placeholder: "Jelszó"} %>
    </li>
  </ul>

  <%= f.submit "Bejelentkezés", class: "pc-button pc-ocean" %>
    <a class="pc-button pc-ocean" data-target="#partner-login-form" data-toggle="collapse">Elrejtés</a>
<% end %>

app/views/home/_registration_form.html.erb
<%= form_for(:user, url: registration_path(:user), html: {class: "flex-form collapse", id: "user-registration-form"}) do |f| %>
  <p class="centered-content text-center">
    Ha Partnerként szeretnél csatlakozni oldalunkhoz, kérlek vedd fel velünk a kapcsolatot a
    <strong class="pc-teal-inverse">contact@psycraft.hu</strong> email címen!
  </p>
  <h2>Regisztráció felhasználóként</h2>
  <ul>
    <li>
      <%= f.label :username, class: "sr-only" %>
      <%= f.text_field :username, placeholder: "Felhasználónév" %>
    </li>
    <li>
      <%= f.label :email, class: "sr-only" %>
      <%= f.email_field :email, placeholder: "Email" %>
    </li>
    <li>
      <%= f.label :password, class: "sr-only" %>
      <%= f.password_field :password, autocomplete: "off", placeholder: "Jelszó" %>
    </li>
    <li>
      <%= f.label :password_confirmation, class: "sr-only" %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: "Jelszó újra" %>
    </li>
  </ul>

  <%= f.submit "Regisztrálok", class: "pc-button pc-blue" %>
  <a class="pc-button pc-blue" data-target="#user-registration-form" data-toggle="collapse">Elrejtés</a>
<% end %>

app/views/home/_user_login_form.html.erb
<%= form_for(:user, url: session_path(:user), html: {class: "flex-form collapse", id: "user-login-form"}) do |f| %>
  <ul>
    <li>
      <%= f.label :login_id, class: "sr-only" %>
      <%= f.text_field :login_id, {autofocus: true, placeholder: "Email vagy felhasználonév"} %>
    </li>
    <li>
      <%= f.label :password, class: "sr-only" %>
      <%= f.password_field :password, {autocomplete: "off", placeholder: "Jelszó"} %>
    </li>
  </ul>

  <%= f.submit "Bejelentkezés", class: "pc-button pc-teal" %>
    <a class="pc-button pc-teal" data-target="#user-login-form" data-toggle="collapse">Elrejtés</a>
<% end %>

app/views/home/index.html.erb
<% unless client_signed_in? %>
  <section id="about">
    <div id="container-outer" class="centered-content pc-transparent">
      <div id="container-inner">
        <%= image_tag("psycraft_logo_color.png", alt: "Logo") %>
        <div id="content">
          <div id="welcome">
            <h2>KEDVES LÁTOGATÓ!</h2>
            <p>
              Üdvözlünk a PsyCraft webes applikáció főoldalán. Örülönk, hogy idetaláltál (még ha csak véletlenül is).
              Jelenleg az oldalunk teszt verzióját látod, ugyanis még gőzerővel dolgozunk azon, hogy mind funkcionalitásban,
              mind kinézetben teljes lehessen.
            </p>
          </div>
          <div id="sign-in">
            <button class="pc-button pc-teal" data-target="#user-login-form" data-toggle="collapse">BEJELENTKEZÉS FELHASZNÁLÓKÉNT</button>
            <%= render(partial: "user_login_form") %>

            <button class="pc-button pc-ocean" data-target="#partner-login-form" data-toggle="collapse">BEJELENTKEZÉS PARTNERKÉNT</button>
            <%= render(partial: "partner_login_form") %>

            <h3>MÉG NINCS FIÓKOD?</h3>
            <button class="pc-button pc-blue" data-target="#user-registration-form" data-toggle="collapse">REGISZTRÁLJ!</button>
            <%= render(partial: "registration_form") %>
          </div>
        </div>
        <h3 id="more-text"><span class="icon-left-line-11"></span> TÖBBET SZERETNÉL TUDNI?</h3>
        <p>Görgess lejjebb!</p>
      </div>
    </div>
  </section>
<% end %>

<section id="us" class="centered-content">
  <span class="icon-up-line"></span>
  <h2>RÓLUNK</h2>
  <p class="text-center">
    A PsyCraft az In Center projektet támogató, annak keretein belül létrejövő online játék, ahol könnyen hozzáférhetsz
    pszichológiai és mentálhigiénés tartalmú előadásokhoz, workshopokhoz. Ha még nem hallottál rólunk, akkor itt bővebb
    információkat találsz:
  </p>
  <a href="http://www.incenter.hu" target="_blank" class="pc-button pc-teal">IN CENTER</a>
</section>

<section id="infos" class="pc-transparent">
  <%= image_tag("library.jpg", alt: "Főoldal kép") %>
  <div id="infos-content">
    <h2><span class="icon-left-line-11"></span> TUDNIVALÓK</h2>
    <p>
      Mint korábban is emlitettük ez egy teszt oldal, ahol az éppen aktuális állapotot teszteljük. Bátran próbáld ki az
      összes lehetőséget, amit kinálunk! Regisztrálj felhasználóként vagy szolgáltatásokat nyújtó partnerként. Hozz
      létre eseményeket, hirdess meg alkalmakat, kommentelj, stb. Fontos, hogy jelenleg a funkciók fejlesztésére,
      bővitésére helyezzük a hangsúlyt.
    </p>
    <h3>ÉSZREVÉTELED, VÉLEMÉNYED VAN AZ OLDALLAL KAPCSOLATBAN?</h3>
    <p>
      Bátran vedd fel velünk a kapcsolatot, jelezd akár kommentben az oldalon, vagy írj egy e-mailt a
      <strong class="pc-teal-inverse">feedback@psycraft.hu</strong> e-mail cimre
      <small>(tárgyként kérlek "PsyCraft feedback" szöveget használd)</small>.
    </p>
    <p>
      Köszönjük közreműködésedet, hogy segitesz az oldalt jobbá, könnyebben használhatóvá tenni! Fontos számunkra a
      visszajelzésed, mivel ezt az oldalt Neked fejlesztjük, hogy segitségével Te tudd magad fejleszteni!
    </p>
    <p>Üdvözlettel, In Center és PsyCraft csapat!</p>
  </div>
</section>